# Generated by Django 5.2.5 on 2026-03-12 11:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('lifetime_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('churn_risk', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('web', 'Web Chat'), ('email', 'Email'), ('voice', 'Voice')], max_length=20)),
                ('content', models.TextField()),
                ('intent_label', models.CharField(blank=True, max_length=100, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('suggested_reply', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('ai_resolved', 'AI Resolved'), ('escalated', 'Escalated to Agent'), ('closed', 'Closed')], default='open', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.customer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
